complete_from_path = true
ctrlc_exit = true
disable_table_indexes = true
filesize_format = "b"
# filesize_metric = true
nonzero_exit_errors = true
pivot_mode = "always"
# rm_always_trash = false
# skip_welcome_message = false

# basic, compact, compact_double, light, thin, with_love,
# rounded, reinforced, heavy, none, other
table_mode = "compact"


startup = [
    "mkdir ~/.cache/starship",
    "starship init nu | save ~/.cache/starship/init.nu",
    "source ~/.cache/starship/init.nu",
    "zoxide init nushell --hook prompt | save ~/.zoxide.nu",
    "source ~/.zoxide.nu",
]
prompt = "starship_prompt"


[line_editor]
auto_add_history = true
bell_style = "visible"
color_mode = "forced"
completion_prompt_limit = 10
completion_type = "list"
edit_mode = "vi"
history_duplicates = "ignoreconsecutive"
history_ignore_space = true
completion_match_method = "case-insensitive"
