sudo dnf install --allowerasing \
  ansible \
  bat \
  below \
  bubblewrap \
  ccache \
  clang-tools-extra \
  clazy \
  cmake{,-{data,doc,fedora,filesystem,rpm-macros}} \
  cscope \
  curl \
  extra-cmake-modules \
  fd-find \
  fish \
  fontconfig{,-devel} \
  freetype{,-devel} \
  fzf \
  gh \
  git \
  git-delta \
  graphite2{,-devel} \
  harfbuzz{,-{icu,devel}} \
  helm \
  incron \
  inotify-tools \
  kubernetes{,-{client,kubeadm}} \
  libcurl{,-devel} \
  libicu{,-{devel,doc}} \
  libpng{,-{devel,static,tools}} \
  libstdc++{,-{devel,docs,static}} \
  libtree-sitter{,-devel} \
  lld \
  lldb \
  llvm \
  luajit{,-devel} \
  meson \
  ncurses{,-{libs,devel,static}} \
  ninja-build \
  openssl-{devel,libs} \
  osquery \
  plocate \
  readline{,-{devel,static}} \
  ripgrep \
  rr \
  sqlite{,-{analyzer,devel,doc,libs}} \
  tmux \
  valgrind \
  watchman \
  wget \
  xz{,-{devel,libs,lzma-compat,static}} \
  zlib{,-{devel,static}}
