complete -c earthly -n "__fish_use_subcommand" -f -a "bootstrap" -d "Bootstraps earthly installation including shell autocompletion and buildkit image download"
complete -c earthly -n "__fish_use_subcommand" -f -a "orgs" -s "org" -d "Earthly organization administration *experimental*"
complete -c earthly -n "__fish_use_subcommand" -f -a "ls" -d "List targets from an Earthfile *experimental*"
complete -c earthly -n "__fish_use_subcommand" -f -a "secrets" -s "secrets" -d "Earthly secrets"
complete -c earthly -n "__fish_use_subcommand" -f -a "account" -d "Create or manage an Earthly account *experimental*"
complete -c earthly -n "__fish_use_subcommand" -f -a "prune" -d "Prune Earthly build cache"
complete -c earthly -n "__fish_use_subcommand" -f -a "config" -d "Edits your Earthly configuration file"
complete -c earthly -n "__fish_use_subcommand" -f -a "satellites" -s "sat" -d "Launch and use a Satellite runner as remote backend for Earthly builds (*experimental*)"
complete -c earthly -n "__fish_use_subcommand" -f -a "preview" -d "Experimental commands that will likely appear in a future release."
complete -c earthly -n "__fish_use_subcommand" -f -a "help" -s "h" -d "Shows a list of commands or help for one command"
